# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("accessibility.typeaheadfind.flashBar", 0);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1400231033);
user_pref("app.update.lastUpdateTime.background-update-timer", 1400231273);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1400231153);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1400234393);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1400230913);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.disk.smart_size.use_old_max", false);
user_pref("browser.cache.disk.smart_size_cached_value", 358400);
user_pref("browser.download.lastDir", "/home/hafizegan");
user_pref("browser.migration.version", 7);
user_pref("browser.pagethumbnails.storage_version", 2);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.smartBookmarksVersion", 4);
user_pref("browser.preferences.advanced.selectedTabIndex", 1);
user_pref("browser.startup.homepage_override.buildID", "20131030234958");
user_pref("browser.startup.homepage_override.mstone", "17.0.10");
user_pref("extensions.blocklist.pingCountTotal", 4);
user_pref("extensions.blocklist.pingCountVersion", 4);
user_pref("extensions.bootstrappedAddons", "{}");
user_pref("extensions.databaseSchema", 14);
user_pref("extensions.enabledAddons", "%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:17.0.10");
user_pref("extensions.installCache", "[{\"name\":\"app-global\",\"addons\":{\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"descriptor\":\"/usr/lib/iceweasel/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"mtime\":1398043112000}}}]");
user_pref("extensions.lastAppVersion", "17.0.10");
user_pref("extensions.lastPlatformVersion", "17.0.10");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.shownSelectionUI", true);
user_pref("idle.lastDailyNotification", 1400232956);
user_pref("intl.charsetmenu.browser.cache", "ISO-8859-1, UTF-8");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.proxy.backup.ftp", "proxy.its.ac.id");
user_pref("network.proxy.backup.ftp_port", 8080);
user_pref("network.proxy.backup.socks", "proxy.its.ac.id");
user_pref("network.proxy.backup.socks_port", 8080);
user_pref("network.proxy.backup.ssl", "proxy.its.ac.id");
user_pref("network.proxy.backup.ssl_port", 8080);
user_pref("network.proxy.ftp", "proxy.its.ac.id");
user_pref("network.proxy.ftp_port", 8080);
user_pref("network.proxy.http", "proxy.its.ac.id");
user_pref("network.proxy.http_port", 8080);
user_pref("network.proxy.share_proxy_settings", true);
user_pref("network.proxy.socks", "proxy.its.ac.id");
user_pref("network.proxy.socks_port", 8080);
user_pref("network.proxy.ssl", "proxy.its.ac.id");
user_pref("network.proxy.ssl_port", 8080);
user_pref("places.database.lastMaintenance", 1400232957);
user_pref("places.history.expiration.transient_current_max_pages", 21024);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1400232957);
user_pref("toolkit.startup.last_success", 1400235728);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1401274182);
user_pref("xpinstall.whitelist.add", "");
user_pref("xpinstall.whitelist.add.180", "");
user_pref("xpinstall.whitelist.add.36", "");
